### ISSUE TITLE
Game crashes upon interacting with any note block

### ISSUE THREAD

**Issue by DragonZaid** [monkeysHK/NoteblockAddons#1]
Game immediately freezes every time upon first interacting with a note block, resulting in a crash. Same results with forge for MC 1.16.3 thru 1.16.5, and with mod version 1.0 and 1.1. The crash not seem to be dependent on other installed mods or the item being held during interaction.

**Comment by MonkeysHK** [comment]
I am so sorry to get to you so late. I was given the attention of this issue very early on, but I had since stopped development on this mod, and I did not personally know anyone who could help look at this issue.
There is a chance I will continue this project with Fabric in the future, and fix this issue. And most importantly thank you for your report.

**Comment by MonkeysHK** [comment]
This issue is most likely fixed in the latest patch.
